
SCREEN_SIZE = (1280 * 2, 720 * 2)
DISPLAY_SIZE = (SCREEN_SIZE[0]//2, SCREEN_SIZE[1]//2)
FPS = 60

TILE_SIZE = 24

PLAYER_SPEED = 1

PLAYER_POS = (50, 50)
PLAYERS_SIZE = (TILE_SIZE, TILE_SIZE)
PLAYERS_IMAGE_SIZE = (PLAYERS_SIZE[0], PLAYERS_SIZE[1])

JUMP_HEIGHT = 3

PHYSICS_TILES = {'grass', 'stone'}
AUTOTILE_TYPES = {'grass', 'stone'}

FONT = None

