
DISPLAY_SIZE = (1280, 720)
FPS = 60

TILE_SIZE = 48

PLAYER_SPEED = 7
JUMP_HEIGHT = 13
GRAVITY = 0.6 


PLAYER_POS = (50, 50)
PLAYERS_SIZE = (TILE_SIZE, TILE_SIZE)
PLAYERS_IMAGE_SIZE = (PLAYERS_SIZE[0], PLAYERS_SIZE[1])

PHYSICS_TILES = {'grass', 'stone'}
AUTOTILE_TYPES = {'grass', 'stone'}

FONT = None

